{{- if not .Values.exporter.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dtr_prometheus_exporter.fullname" . }}
  labels:
    app: {{ template "dtr_prometheus_exporter.name" . }}
    chart: {{ template "dtr_prometheus_exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  dtr-user: {{ .Values.exporter.dtrUser | b64enc | quote }}
  dtr-password: {{ .Values.exporter.dtrPassword | b64enc | quote }}
{{- end }}
