apiVersion: v1
kind: Service
metadata:
  name: {{ template "dtr_prometheus_exporter.fullname" . }}
  labels:
    app: {{ template "dtr_prometheus_exporter.name" . }}
    chart: {{ template "dtr_prometheus_exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "dtr_prometheus_exporter.name" . }}
    release: {{ .Release.Name }}